name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'go/**'

jobs:
  go-tests:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: changes
        uses: jitterbit/get-changed-files@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'  # Specify your Go version here

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - name: Run Go Tests
        run: cd go && go test ./...