name: PR Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: changes
        uses: jitterbit/get-changed-files@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version here

      - name: Set Environment Variable
        run: echo "TEST_ANSWER=${{ secrets.TEST_ANSWER }}" >> $GITHUB_ENV

      - name: Run Python Tests
        run: |
          cd python
          python3 solution.test.py